apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opencti-ing
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  tls:
    - hosts:
      - {{ .Values.domainOpenCti }}
  rules:
    - host: {{ .Values.domainOpenCti }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opencti-main-server
                port:
                  number: 80
