apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opencti-ing
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  tls:
    - hosts:
      - {{ .Values.domainFileDistributor }}
  rules:
    - host: {{ .Values.domainFileDistributor }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.nameOverride }}
                port:
                  number: {{ .Values.nginx.service.port }}
