apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maxmind-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: maxmind-secret       # name of the k8s Secret to be created
  data:
  - secretKey: MAXMIND_LICENSE_KEY
    remoteRef:
      key: initial-secret-preset
      property: MAXMIND_LICENSE_KEY
