apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: minio-secret      # name of the k8s Secret to be created
  data:
  - secretKey: rootUser
    remoteRef:
      key: initial-secret
      property: GRAFANA_USER #ยืม grafana มาใช้

  - secretKey: rootPassword
    remoteRef:
      key: initial-secret
      property: GRAFANA_PASSWORD #ยืม grafana มาใช้
