apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: logstash-etl
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          custom: "true"
  template:
    metadata:
      name: 'logstash-etl-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/wintech-thai/please-protect-center-data-plane.git
        targetRevision: "{{name}}" #Based on environment
        path: 'manifests/logstash-etl'
      destination:
        name: in-cluster
        namespace: logstash-etl
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
